#url of the apigateway server which is how the database is accessed. You cna find this by . . . .
APIgatewayurl: "http://127.0.0.1:5000/"
#url of the multimedia file server should just be base url 
webserverurl: "http://172.19.0.1:8080/"
#port rfid start and stop signals will be sent 
rfidport: 65432
# IP address that will be sending the start and stop signals 
# if empty string the program will look at all IP addresses
rfidhost: ""
#list of RTSP urls for the cameras attached to the toolboxes
# the placement of the url in the list should correspond to the toolbox number
RTSP: 
    - "rtsp://admin:NullTerminat0r2%24@192.168.0.17/onvif1"
    - "drawer316_1.avi"
#list of labels of onnx classes
#placement in list should correspond to the valuei n the return of te onnx file 
onnxlabels:
  - "crescent wrench"
  - "flatheadSD"
  - "hammer"
  - "hand"
  - "handsaw"
  - "mallet"
  - "philipsSD"
  - "pliers"
  - "ratchet"
  - "shadowbox"
  - "shadowboxTest"
  - "socketset"
  - "socketSolo"
  - "tapemeasure"
# list of tools that the onnx file has classes for, order does not matter
onnxtools: 
  - "crescent wrench"
  - "flatheadSD"
  - "hammer"
  - "handsaw"
  - "mallet"
  - "philipsSD"
  - "pliers"
  - "ratchet"
  - "socketset"
  - "socketSolo"
  - "tapemeasure"

#list of non-tools that onnx has classes for, order does not matter
onnxnontools: 
  - "hands"
  - "shadowbox"
  - "shadowboxTest"
#similarity threshold for template matching with drawer symbols and the symbol check function
thresholdsymbol: .8
#similarity threshold for template matching with the tools
thresholdtool: .7
#maximum rotation to try to findd the template match clockwise and counter clockwise
degrees: 0
#fraction of degree to rotate ie if 10 it will rotate a tenth of a degree uand template match until a match that meets
# the threshold is found or it has reached the mximum amount of degrees 
# making it 0 will result in an error
degreesdiv: 1
#file location of the onnx classifier after webserver base url
onnxfile: "ClassifierInputData/hiline_class.onnx"
# amount of tool that must be in frame to be considered visible should be form 0 to 1
buffer: 0.2
#how many pixels to exapns the horizontal start and end of the tool space in the images to be template matched by
# Should be at a minimium the number of pixels that makes up the x direction of the side of the drawer between the
# drawer symbols and the shadow box of the drawer.
bufferx: 100
#how many pixels to exapand the vertical start and end of the tool space in the images to be template matched by
buffery: 20
#If similarity above this number ignore result of onnx file not matching tool type
thresholdignoreonnx: .85
#If the onnxclassifier  recognizes the image as a nontool add this much to the confidence interval of tool checked out to see if it is now greater than the tool checked in
thresholdadd: .1
#multiplied by buffery to calculate area in which the drawer symbol should be on the y axis
multfordrawersymbolbuffer: 10
#frames per second of the RTSP stream or given video
fps: 10